import { placeholderImage } from "./placeholder";
import type { Listing } from "./types";

const RAW: Omit<Listing, "images">[] = [
  {
    id: "l5",
    type: "TRADE",
    title: "Lamborghini Countach - Mainline Loose Bundle x5, Trade",
    description:
      "Bundle of 5 loose Countach castings, different colorways, all played-with condition — great for customizers or track builds. Looking to trade the lot, not selling.",
    castingName: "Lamborghini Countach",
    series: "Mainline",
    condition: "PLAYED",
    wantsInExchange: "Any Japanese or European sports car mainline castings, similar quantity",
    city: "Hyderabad",
    status: "ACTIVE",
    views: 289,
    likes: 11,
    seller: { name: "Neha P.", city: "Hyderabad", rating: 4.5, dealsCompleted: 15 },
    createdAt: "2026-08-25T18:20:00Z",
  },
  {
    id: "t1",
    type: "TRADE",
    title: "Datsun 240Z - Looking to swap for a Skyline",
    description:
      "Mint Datsun 240Z, mainline red. Have two of these — happy to trade for any R32/R33/R34 Skyline in similar condition, mainline or premium.",
    castingName: "Datsun 240Z",
    series: "Mainline",
    condition: "MINT",
    wantsInExchange: "Any Nissan Skyline GT-R (R32/R33/R34), mainline or premium, mint condition",
    city: "Mumbai",
    status: "ACTIVE",
    views: 267,
    likes: 14,
    seller: { name: "Sana W.", city: "Mumbai", rating: 4.8, dealsCompleted: 29 },
    createdAt: "2026-08-27T07:00:00Z",
  },
  {
    id: "t2",
    type: "TRADE",
    title: "'55 Chevy Bel Air - Want Treasure Hunt cars",
    description:
      "Loose but clean '55 Bel Air, wheels roll great. Building a Treasure Hunt collection — will trade for any regular or Super TH, or a small stack of mainline TH cars.",
    castingName: "'55 Chevy Bel Air",
    series: "Mainline",
    condition: "GOOD",
    wantsInExchange: "Any Treasure Hunt or Super Treasure Hunt casting",
    city: "Delhi",
    status: "ACTIVE",
    views: 344,
    likes: 21,
    seller: { name: "Farhan I.", city: "Delhi", rating: 4.6, dealsCompleted: 18 },
    createdAt: "2026-08-26T13:20:00Z",
  },
  {
    id: "t3",
    type: "TRADE",
    title: "Premium BMW M3 GTR - Trade for RLC piece",
    description:
      "Sealed Premium BMW M3 GTR (Most Wanted livery). Chasing an RLC exclusive for my collection — open to any RLC car, will consider adding cash on my end for the right one.",
    castingName: "BMW M3 GTR",
    series: "Premium",
    condition: "MINT",
    wantsInExchange: "Any RLC (Red Line Club) exclusive casting",
    city: "Bengaluru",
    status: "ACTIVE",
    views: 478,
    likes: 29,
    seller: { name: "Priya D.", city: "Bengaluru", rating: 4.9, dealsCompleted: 41 },
    createdAt: "2026-08-28T09:40:00Z",
  },
  {
    id: "t4",
    type: "TRADE",
    title: "Duplicate JDM Lot (4 cars) - Trade for muscle cars",
    description:
      "Four duplicate JDM mainline castings (Supra, RX-7, S2000, Silvia), all near mint. Looking to trade the lot for American muscle — Mustangs, Camaros, Challengers.",
    series: "Mainline",
    condition: "NEAR_MINT",
    wantsInExchange: "American muscle mainline cars (Mustang, Camaro, Challenger), similar count",
    city: "Pune",
    status: "ACTIVE",
    views: 205,
    likes: 9,
    seller: { name: "Kabir T.", city: "Pune", rating: 4.8, dealsCompleted: 37 },
    createdAt: "2026-08-25T15:10:00Z",
  },
  {
    id: "l10",
    type: "TRADE",
    title: "Toyota Supra Mk4 - Twin Turbo, Trade Only",
    description:
      "Mainline Toyota Supra Mk4, orange with twin-turbo callout on the side. Near mint, wheels roll true. Looking for something specific, not selling this one.",
    castingName: "Toyota Supra Mk4",
    series: "Mainline",
    condition: "NEAR_MINT",
    wantsInExchange: "A Tooned or Custom series casting, mint condition",
    city: "Delhi",
    status: "ACTIVE",
    views: 176,
    likes: 6,
    seller: { name: "Rohan S.", city: "Delhi", rating: 4.7, dealsCompleted: 104 },
    createdAt: "2026-08-27T11:00:00Z",
  },
];

// Real cars from the user's own collection.
const MY_LISTINGS: Listing[] = [
  {
    id: "m1",
    type: "TRADE",
    title: "Toyota MR2 - Tooned #94 - Trade for a Supra",
    description:
      "Toyota MR2 in the Tooned series, black with orange/yellow racing livery and orange-rimmed wheels. #222/250, Tooned 5/5. Still factory sealed on card, never opened. Looking to trade for a Toyota Supra casting, any series.",
    castingName: "Toyota MR2",
    series: "Tooned",
    condition: "MINT",
    wantsInExchange: "A Toyota Supra casting, any series, similar condition",
    city: "Kochi",
    status: "ACTIVE",
    images: ["/listings/mr2-tooned.jpg"],
    views: 94,
    likes: 5,
    seller: { name: "You", city: "Kochi", rating: 5.0, dealsCompleted: 0 },
    createdAt: "2026-08-29T06:00:00Z",
  },
  {
    id: "m2",
    type: "TRADE",
    title: "Aston Martin Aramco F1 Team - Formula 1 series, Trade",
    description:
      "Aston Martin Aramco Formula One Team car, metallic teal green. Formula 1 series 5/5, #185/250. Still factory sealed on card, never opened.",
    castingName: "Aston Martin Aramco Formula One Team",
    series: "Formula 1",
    condition: "MINT",
    wantsInExchange: "Any Formula 1 or Premium series casting I don't already have",
    city: "Kochi",
    status: "ACTIVE",
    images: ["/listings/aston-martin-f1.jpg"],
    views: 63,
    likes: 4,
    seller: { name: "You", city: "Kochi", rating: 5.0, dealsCompleted: 0 },
    createdAt: "2026-08-29T06:05:00Z",
  },
];

const AUCTIONS_RAW: Omit<Listing, "images">[] = [
  {
    id: "a1",
    type: "AUCTION",
    title: "Custom Olds 442 - Redline Build, Live Auction",
    description:
      "One-off custom real riders build on an Olds 442 casting, hand-painted spectraflame orange. Bidding closes soon — highest bid wins, no reserve.",
    castingName: "Olds 442",
    series: "Custom",
    condition: "GOOD",
    startingBidInr: 2000,
    bidIncrementInr: 200,
    city: "Mumbai",
    status: "ACTIVE",
    views: 940,
    likes: 41,
    seller: { name: "Arjun M.", city: "Mumbai", rating: 4.9, dealsCompleted: 62 },
    createdAt: "2026-08-29T14:00:00Z",
    endsAt: "2026-08-31T10:00:00Z",
  },
  {
    id: "a2",
    type: "AUCTION",
    title: "Sealed Case-Fresh RLC Datsun 620 - 4-Day Auction",
    description:
      "Case-fresh RLC Datsun 620, never touched outside the mailer box. Starting low to get bidding going — Buy Now available if you don't want to wait.",
    castingName: "Datsun 620",
    series: "RLC",
    condition: "MINT",
    startingBidInr: 8000,
    bidIncrementInr: 500,
    buyNowInr: 15000,
    city: "Bengaluru",
    status: "ACTIVE",
    views: 611,
    likes: 35,
    seller: { name: "Divya K.", city: "Bengaluru", rating: 5.0, dealsCompleted: 21 },
    createdAt: "2026-08-29T08:00:00Z",
    endsAt: "2026-09-03T12:00:00Z",
  },
  {
    id: "a3",
    type: "AUCTION",
    title: "Vintage '68 Custom Camaro - Auction Ended",
    description:
      "Hand-built '68 Camaro custom on a real riders chassis, near mint. Auction has closed — shown here for reference.",
    castingName: "'68 Camaro",
    series: "Custom",
    condition: "NEAR_MINT",
    startingBidInr: 1500,
    bidIncrementInr: 150,
    city: "Delhi",
    status: "SOLD",
    views: 733,
    likes: 52,
    seller: { name: "Rohan S.", city: "Delhi", rating: 4.7, dealsCompleted: 104 },
    createdAt: "2026-08-27T10:00:00Z",
    endsAt: "2026-08-29T18:00:00Z",
  },
];

export const MOCK_LISTINGS: Listing[] = [
  ...MY_LISTINGS,
  ...RAW.map((r) => ({
    ...r,
    images: [
      placeholderImage(r.id + "-1", r.castingName ?? r.title),
      placeholderImage(r.id + "-2", r.castingName ?? r.title),
    ],
  })),
  ...AUCTIONS_RAW.map((r) => ({
    ...r,
    images: [
      placeholderImage(r.id + "-1", r.castingName ?? r.title),
      placeholderImage(r.id + "-2", r.castingName ?? r.title),
    ],
  })),
];
